// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCJfBrqd4dO8pxkEjdEhVeYQvFuJWTYkw',
    appId: '1:569284477850:web:0c4a26364eda739c0e7023',
    messagingSenderId: '569284477850',
    projectId: 'yo-lda-a732c',
    authDomain: 'yo-lda-a732c.firebaseapp.com',
    storageBucket: 'yo-lda-a732c.appspot.com',
    measurementId: 'G-G30X4T7MSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvNC-An2SXHYbsG_lr7RgNhQBLwhVFYP8',
    appId: '1:569284477850:android:b225be5494f6f1c60e7023',
    messagingSenderId: '569284477850',
    projectId: 'yo-lda-a732c',
    storageBucket: 'yo-lda-a732c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6ZdynAnwpXTdm_gShFQoyAgGRDGuVPRg',
    appId: '1:569284477850:ios:70935f1ad83b91860e7023',
    messagingSenderId: '569284477850',
    projectId: 'yo-lda-a732c',
    storageBucket: 'yo-lda-a732c.appspot.com',
    iosBundleId: 'com.example.yolda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6ZdynAnwpXTdm_gShFQoyAgGRDGuVPRg',
    appId: '1:569284477850:ios:70935f1ad83b91860e7023',
    messagingSenderId: '569284477850',
    projectId: 'yo-lda-a732c',
    storageBucket: 'yo-lda-a732c.appspot.com',
    iosBundleId: 'com.example.yolda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCJfBrqd4dO8pxkEjdEhVeYQvFuJWTYkw',
    appId: '1:569284477850:web:74b114b643bebc890e7023',
    messagingSenderId: '569284477850',
    projectId: 'yo-lda-a732c',
    authDomain: 'yo-lda-a732c.firebaseapp.com',
    storageBucket: 'yo-lda-a732c.appspot.com',
    measurementId: 'G-YP8YPX3ZYY',
  );
}
